/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    members: Member;
    events: Event;
    tracks: Track;
    categories: Category;
    media: Media;
    audio: Audio;
    'contact-requests': ContactRequest;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    members: MembersSelect<false> | MembersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    tracks: TracksSelect<false> | TracksSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    audio: AudioSelect<false> | AudioSelect<true>;
    'contact-requests': ContactRequestsSelect<false> | ContactRequestsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    hero: Hero;
    about: About;
    'repertoire-section': RepertoireSection;
    'contact-section': ContactSection;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    hero: HeroSelect<false> | HeroSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'repertoire-section': RepertoireSectionSelect<false> | RepertoireSectionSelect<true>;
    'contact-section': ContactSectionSelect<false> | ContactSectionSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  /**
   * 1 = primer violín, 2 = segundo violín, 3 = viola, 4 = violonchelo.
   */
  order: number;
  name: string;
  instrument: 'violin' | 'viola' | 'cello';
  /**
   * Se lee en la tira del retrato. Ej.: «Jesús Medina».
   */
  shortName: string;
  bio: string;
  photo: number | Media;
  /**
   * Valor de object-position: dónde queda la cara dentro del recorte. Ej.: «50% 28%».
   */
  photoPosition?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Lo que lee un lector de pantalla y lo que se muestra si la foto no carga.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Desmarcada, la presentación se guarda pero no aparece en la portada. Útil para prepararla antes de anunciarla.
   */
  published?: boolean | null;
  title: string;
  date: string;
  /**
   * Formato de 24 horas, ej.: 19:30.
   */
  time: string;
  city: string;
  image: number | Media;
  /**
   * Valor de object-position. Ej.: «46% 42%».
   */
  imagePosition?: string | null;
  /**
   * Se muestra en la ventana que abre la tarjeta. Los saltos de línea se respetan.
   */
  description?: string | null;
  program?:
    | {
        title: string;
        composer?: string | null;
        id?: string | null;
      }[]
    | null;
  venue?: {
    name?: string | null;
    address?: string | null;
    /**
     * Opcional: vacío, el enlace «Cómo llegar» se arma con recinto, dirección y ciudad.
     */
    mapsUrl?: string | null;
  };
  tickets?: {
    /**
     * Con enlace, la ventana muestra «Comprar boletos»; sin él, «Solicitar informes» lleva al formulario.
     */
    url?: string | null;
    /**
     * Uno por tipo de entrada; se muestran en fila, separados por un punto.
     */
    prices?:
      | {
          /**
           * Ej.: «$250» o «Sin costo».
           */
          amount: string;
          /**
           * Ej.: «general», «estudiantes y maestros», «menores de 12 años».
           */
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracks".
 */
export interface Track {
  id: number;
  order: number;
  title: string;
  composer: string;
  /**
   * Las categorías se editan en Contenido › Categorías.
   */
  category: number | Category;
  /**
   * Sin grabación, la obra se lista pero no se puede reproducir.
   */
  audio?: (number | null) | Audio;
  /**
   * Se muestra mientras el navegador lee la duración real; con grabación, manda el archivo.
   */
  durationSeconds: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Las pestañas del repertorio, 5 como máximo. «Todo» siempre va primero y no se edita.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Orden de las pestañas, de izquierda a derecha.
   */
  order: number;
  /**
   * Se muestra en la tarjeta de la obra que suena. Ej.: «Clásico y cámara».
   */
  label: string;
  /**
   * Lo que se lee en la pestaña del filtro; vacía, se usa el nombre completo. Ej.: «Cámara».
   */
  shortLabel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * MP3, M4A, OGG o WAV. Se asignan a las obras en Contenido › Repertorio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio".
 */
export interface Audio {
  id: number;
  /**
   * Ej.: «Borodin — Notturno (fragmento)».
   */
  title: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-requests".
 */
export interface ContactRequest {
  id: number;
  status: 'new' | 'answered' | 'discarded';
  name: string;
  contact: string;
  eventType: 'concierto' | 'boda' | 'ceremonia' | 'privado';
  date?: string | null;
  place?: string | null;
  details?: string | null;
  /**
   * Sólo las ve el equipo: qué se respondió, propuesta enviada, etc.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'tracks';
        value: number | Track;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audio';
        value: number | Audio;
      } | null)
    | ({
        relationTo: 'contact-requests';
        value: number | ContactRequest;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  order?: T;
  name?: T;
  instrument?: T;
  shortName?: T;
  bio?: T;
  photo?: T;
  photoPosition?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  published?: T;
  title?: T;
  date?: T;
  time?: T;
  city?: T;
  image?: T;
  imagePosition?: T;
  description?: T;
  program?:
    | T
    | {
        title?: T;
        composer?: T;
        id?: T;
      };
  venue?:
    | T
    | {
        name?: T;
        address?: T;
        mapsUrl?: T;
      };
  tickets?:
    | T
    | {
        url?: T;
        prices?:
          | T
          | {
              amount?: T;
              label?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracks_select".
 */
export interface TracksSelect<T extends boolean = true> {
  order?: T;
  title?: T;
  composer?: T;
  category?: T;
  audio?: T;
  durationSeconds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  order?: T;
  label?: T;
  shortLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio_select".
 */
export interface AudioSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-requests_select".
 */
export interface ContactRequestsSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  contact?: T;
  eventType?: T;
  date?: T;
  place?: T;
  details?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  /**
   * Se muestra en mayúsculas con la fuente de display.
   */
  title: string;
  lead: string;
  image: number | Media;
  /**
   * Valor de object-position del recorte en el teléfono, donde la foto se corta por los lados para que el cuarteto llene el ancho. El primer número mueve el recorte: más alto, más a la derecha. Ej.: «82% 50%». En escritorio la foto se ve completa.
   */
  imagePosition?: string | null;
  /**
   * Sólo se ve en el teléfono, entre el botón «Escuchar» y las tarjetas. En escritorio nombra la lista para los lectores de pantalla.
   */
  eventsHeading: string;
  listenLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  title: string;
  lead: string;
  photo: number | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "repertoire-section".
 */
export interface RepertoireSection {
  id: number;
  title: string;
  /**
   * Junto a las obras que aún no tienen archivo de audio.
   */
  unavailableLabel: string;
  emptyState: {
    title: string;
    text: string;
    ctaLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-section".
 */
export interface ContactSection {
  id: number;
  eyebrow: string;
  title: string;
  lead: string;
  notice: string;
  sentTitle: string;
  sentText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tagline: string;
  email: string;
  /**
   * Sólo dígitos con código de país, ej.: 522291234567. Vacío = «por confirmar».
   */
  whatsapp?: string | null;
  location: string;
  locationFull: string;
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    youtube?: string | null;
  };
  photoCredit: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  image?: T;
  imagePosition?: T;
  eventsHeading?: T;
  listenLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "repertoire-section_select".
 */
export interface RepertoireSectionSelect<T extends boolean = true> {
  title?: T;
  unavailableLabel?: T;
  emptyState?:
    | T
    | {
        title?: T;
        text?: T;
        ctaLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-section_select".
 */
export interface ContactSectionSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lead?: T;
  notice?: T;
  sentTitle?: T;
  sentText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tagline?: T;
  email?: T;
  whatsapp?: T;
  location?: T;
  locationFull?: T;
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        youtube?: T;
      };
  photoCredit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}