import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import { forum, fratresDisplay, ttHoves } from "./fonts";
import { GoogleAnalytics } from "@/components/site/shared/google-analytics.comp";
import { SITE_NAME, SITE_TAGLINE } from "@/constants/site.const";
import { SITE_URL } from "@/lib/site-url";

// `metadataBase` is what lets the canonical and the Open Graph image be
// relative paths. The OG image is generated by `opengraph-image.tsx`.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: `${SITE_NAME} | Cuarteto de cuerdas en Veracruz`,
  description:
    "Cuarteto de cuerdas con base en Boca del Río, Veracruz. Música de cámara preparada obra por obra para salas de concierto, ceremonias y celebraciones.",
  keywords: ["cuarteto de cuerdas", "música de cámara", "Veracruz", "bodas", "conciertos", "Cuarteto Fratres"],
  openGraph: {
    siteName: SITE_NAME,
    title: SITE_NAME,
    description: SITE_TAGLINE,
    type: "website",
    locale: "es_MX",
  },
  twitter: {
    card: "summary_large_image",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="es" className={`${forum.variable} ${ttHoves.variable} ${fratresDisplay.variable}`}>
      <body>
        <a className="skip-link" href="#contenido">
          Saltar al contenido
        </a>
        {children}
        <GoogleAnalytics />
        {/* Its script only exists on Vercel deployments; elsewhere it produced a console 404 on every visit. */}
        {process.env.VERCEL === "1" && <Analytics />}
      </body>
    </html>
  );
}
